package greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import greendao.PLocation;
import greendao.MyLocation;
import greendao.SharePrefs;

import greendao.PLocationDao;
import greendao.MyLocationDao;
import greendao.SharePrefsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig pLocationDaoConfig;
    private final DaoConfig myLocationDaoConfig;
    private final DaoConfig sharePrefsDaoConfig;

    private final PLocationDao pLocationDao;
    private final MyLocationDao myLocationDao;
    private final SharePrefsDao sharePrefsDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        pLocationDaoConfig = daoConfigMap.get(PLocationDao.class).clone();
        pLocationDaoConfig.initIdentityScope(type);

        myLocationDaoConfig = daoConfigMap.get(MyLocationDao.class).clone();
        myLocationDaoConfig.initIdentityScope(type);

        sharePrefsDaoConfig = daoConfigMap.get(SharePrefsDao.class).clone();
        sharePrefsDaoConfig.initIdentityScope(type);

        pLocationDao = new PLocationDao(pLocationDaoConfig, this);
        myLocationDao = new MyLocationDao(myLocationDaoConfig, this);
        sharePrefsDao = new SharePrefsDao(sharePrefsDaoConfig, this);

        registerDao(PLocation.class, pLocationDao);
        registerDao(MyLocation.class, myLocationDao);
        registerDao(SharePrefs.class, sharePrefsDao);
    }
    
    public void clear() {
        pLocationDaoConfig.getIdentityScope().clear();
        myLocationDaoConfig.getIdentityScope().clear();
        sharePrefsDaoConfig.getIdentityScope().clear();
    }

    public PLocationDao getPLocationDao() {
        return pLocationDao;
    }

    public MyLocationDao getMyLocationDao() {
        return myLocationDao;
    }

    public SharePrefsDao getSharePrefsDao() {
        return sharePrefsDao;
    }

}
