package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PLOCATION.
 */
public class PLocation {

    private Long id;
    private Long svId;
    private Double latitude;
    private Double longitude;
    private Boolean isDelete;
    private String timeStamp;
    private String CSGTType;
    private String type;
    private Integer count;
    private Integer status;
    private Boolean isReported;
    private String note;
    private boolean isEnter;

    public PLocation() {
    }

    public PLocation(Long id) {
        this.id = id;
    }

    public PLocation(Long id, Long svId, Double latitude, Double longitude, Boolean isDelete, String timeStamp, String CSGTType, String type, Integer count, Integer status, Boolean isReported, String note, boolean isEnter) {
        this.id = id;
        this.svId = svId;
        this.latitude = latitude;
        this.longitude = longitude;
        this.isDelete = isDelete;
        this.timeStamp = timeStamp;
        this.CSGTType = CSGTType;
        this.type = type;
        this.count = count;
        this.status = status;
        this.isReported = isReported;
        this.note = note;
        this.isEnter = isEnter;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getSvId() {
        return svId;
    }

    public void setSvId(Long svId) {
        this.svId = svId;
    }

    public Double getLatitude() {
        return latitude;
    }

    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    public Double getLongitude() {
        return longitude;
    }

    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    public Boolean getIsDelete() {
        return isDelete;
    }

    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    public String getTimeStamp() {
        return timeStamp;
    }

    public void setTimeStamp(String timeStamp) {
        this.timeStamp = timeStamp;
    }

    public String getCSGTType() {
        return CSGTType;
    }

    public void setCSGTType(String CSGTType) {
        this.CSGTType = CSGTType;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Integer getCount() {
        return count;
    }

    public void setCount(Integer count) {
        this.count = count;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Boolean getIsReported() {
        return isReported;
    }

    public void setIsReported(Boolean isReported) {
        this.isReported = isReported;
    }

    public String getNote() {
        return note;
    }

    public void setNote(String note) {
        this.note = note;
    }

    public boolean getIsEnter() {
        return isEnter;
    }

    public void setIsEnter(boolean isEnter) {
        this.isEnter = isEnter;
    }

}
